name: Deploy main

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install
        run: bun install

      - name: format
        run: bun run format:check

      - name: lint
        run: bun run lint:check

      - name: Build
        run: bun run build

      - name: Build site
        run: bun run build

      - name: Deploy to BunnyCDN
        uses: ayeressian/bunnycdn-storage-deploy@v2.2.5
        with:
          source: "dist"
          storageZoneName: "${{ secrets.BUNNY_STORAGE_ZONE }}"
          storagePassword: "${{ secrets.BUNNY_STORAGE_PASSWORD }}"
          storageEndpoint: "${{secrets.BUNNY_STORAGE_ENDPOINT}}"
          accessKey: "${{ secrets.BUNNY_API_KEY }}"
          pullZoneId: "${{ secrets.BUNNY_PULL_ZONE_ID }}"
          upload: "true"
          remove: "true"
          purgePullZone: "true"
